# Generated by Django 2.2.7 on 2019-12-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonMap',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('pokeid', models.CharField(max_length=10)),
                ('current_rank', models.IntegerField()),
                ('old_rand', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon', to='categories.Category')),
            ],
        ),
    ]
