# Generated by Django 2.2.7 on 2019-12-01 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonmap',
            old_name='old_rand',
            new_name='old_rank',
        ),
    ]
