# Generated by Django 2.2.7 on 2019-12-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20191201_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmap',
            name='pokeid',
            field=models.IntegerField(),
        ),
    ]
