# Generated by Django 2.2.7 on 2019-12-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20191202_1638'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pokemonmap',
            constraint=models.UniqueConstraint(fields=('pokeid', 'category'), name='pokecategory'),
        ),
    ]
